### ISSUE TITLE
problem with mysql on centos 8.2

### ISSUE THREAD

**Issue by slhotellier** [chadgeary/guacamole#1]
Hello 
I just have a problem with database configuration due to restriction for use of password on command line.
I make a test removing -p{{ guacdb_root_pass.stdout }} on line 138 but it doesn't seems to work.

thanks for the job and for any help you can give me.

Stéphane

**Comment by chadgeary** [comment]
the mysqld docker container has also changed in the time this issue was opened - I've updated the playbook to pass an environment variable to the container to set the initial root pass and the line you mentioned is no longer required.

If you're using docker, you could use docker secrets. Podman does not currently support them.
